### ISSUE TITLE
Scan Players -> tmp_player.json could not be opend

### ISSUE THREAD

**Issue by christoph5180** [Liver64/LoxBerry-Sonos#16]
I get the following log when I scan for players.
~~~~
OK: 20:19:33 Sonos Plugin has been successfully loaded.
20:19:35 Read main settings from sonos.ini for language: de
20:19:35 The Sonos config file has been loaded
20:19:35 The Sonos player file has been loaded
20:19:35 Loxone Miniserver(s) has been detected
20:19:37 0 Radio Stations has been loaded.
20:19:37 0 Sonos players has been loaded.
20:19:35 Read main settings from sonos.ini for language: de
20:19:35 The Sonos config file has been loaded
20:19:35 The Sonos player file has been loaded
20:19:35 Loxone Miniserver(s) has been detected
20:19:37 0 Radio Stations has been loaded.
20:19:37 0 Sonos players has been loaded.
[07-Sep-2018 20:19:37 Europe/Berlin] PHP Fatal error: Uncaught Error: Call to undefined method LBLog::newLog() in /opt/loxberry/webfrontend/html/plugins/sonos4lox/system/logging.php:23
Stack trace:
#0 /opt/loxberry/webfrontend/html/plugins/sonos4lox/system/network.php(27): LOGGING('Initial network...', 5)
#1 {main}
thrown in /opt/loxberry/webfrontend/html/plugins/sonos4lox/system/logging.php on line 23
[07-Sep-2018 20:19:37 Europe/Berlin] PHP Fatal error: Uncaught Error: Call to undefined method LBLog::newLog() in /opt/loxberry/webfrontend/html/plugins/sonos4lox/system/logging.php:23
Stack trace:
#0 /opt/loxberry/webfrontend/html/plugins/sonos4lox/system/network.php(27): LOGGING('Initial network...', 5)
#1 {main}
thrown in /opt/loxberry/webfrontend/html/plugins/sonos4lox/system/logging.php on line 23
ERROR: 20:19:37 File: tmp_player.json could not be opened! Please execute Scan Zones again.
20:19:37 List of available Miniserver(s) has been successful loaded
20:19:37 List of MP3 files has been successful loaded
OK: 20:19:37 Sonos Plugin has been successfully loaded.
ERROR: 20:19:37 File: tmp_player.json could not be opened! Please execute Scan Zones again.
20:19:37 List of available Miniserver(s) has been successful loaded
20:19:37 List of MP3 files has been successful loaded
OK: 20:19:37 Sonos Plugin has been successfully loaded.
~~~~

**Comment by Liver64** [comment]
Please update the LoxBerry and then the Sonos Plugin to latest release, then the issue should be solved

**Comment by christoph5180** [comment]
Ok, now I get the following Error.
LoxBerry V1.2.3.2
Sonos4lox: v3.4.6
~~~~
OK: 20:57:30 Sonos Plugin has been successfully loaded.
20:57:32 Read main settings from sonos.ini for language: de
20:57:32 The Sonos config file has been loaded
20:57:32 The Sonos player file has been loaded
20:57:32 Loxone Miniserver(s) has been detected
20:57:34 0 Radio Stations has been loaded.
20:57:34 0 Sonos players has been loaded.
20:57:32 Read main settings from sonos.ini for language: de
20:57:32 The Sonos config file has been loaded
20:57:32 The Sonos player file has been loaded
20:57:32 Loxone Miniserver(s) has been detected
20:57:34 0 Radio Stations has been loaded.
20:57:34 0 Sonos players has been loaded.
[07-Sep-2018 20:57:34 Europe/Berlin] PHP Fatal error: Uncaught Error: Call to a member function getTags() on boolean in /opt/loxberry/webfrontend/html/plugins/sonos4lox/system/vendor/duncan3dc/sonos/src/Network.php:279
Stack trace:
#0 /opt/loxberry/webfrontend/html/plugins/sonos4lox/system/network.php(30): duncan3dc\Sonos\Network->getSpeakers()
#1 {main}
thrown in /opt/loxberry/webfrontend/html/plugins/sonos4lox/system/vendor/duncan3dc/sonos/src/Network.php on line 279
[07-Sep-2018 20:57:34 Europe/Berlin] PHP Fatal error: Uncaught Error: Call to a member function getTags() on boolean in /opt/loxberry/webfrontend/html/plugins/sonos4lox/system/vendor/duncan3dc/sonos/src/Network.php:279
Stack trace:
#0 /opt/loxberry/webfrontend/html/plugins/sonos4lox/system/network.php(30): duncan3dc\Sonos\Network->getSpeakers()
#1 {main}
thrown in /opt/loxberry/webfrontend/html/plugins/sonos4lox/system/vendor/duncan3dc/sonos/src/Network.php on line 279
ERROR: 20:57:34 File: tmp_player.json could not be opened! Please execute Scan Zones again.
20:57:34 List of available Miniserver(s) has been successful loaded
20:57:34 List of MP3 files has been successful loaded
OK: 20:57:34 Sonos Plugin has been successfully loaded.
ERROR: 20:57:34 File: tmp_player.json could not be opened! Please execute Scan Zones again.
20:57:34 List of available Miniserver(s) has been successful loaded
20:57:34 List of MP3 files has been successful loaded
OK: 20:57:34 Sonos Plugin has been successfully loaded.
~~~~

**Comment by AngelNev** [comment]
Hallo... 
nur zur Info: ich habe bei mir aktuell das gleiche Problem wie christoph5180
Plugin auch schon deinstalliert und neu installiert.

LoxBerry V1.2.3.2 (als VM auf einem Synology)
Sonos4lox: v3.4.6

![grafik](https://user-images.githubusercontent.com/32057732/45319579-72998c00-b540-11e8-91c1-0a97e0a7f382.png)

**Comment by christoph5180** [comment]
Hallo AngelNev,
ich habe mich jetzt soweit belesen und herausgefunden, dass es scheinbar mit dem letzten Sonos Update zu tun hat. Sonos hat einige Änderungen an den zur Verfügung stehenden Funktionen vorgenommen. Hoffen wir das Liver64 es schafft, dass Sonos4Lox wieder problemlos funktioniert.

**Comment by Liver64** [comment]
Ich arbeite daran. Mit der Sonos V9.1 wurde ein elementarer Bestandteil gelöscht

**Comment by Liver64** [comment]
Ihr könnt hier mal schauen ob der Workaround bei euch funktioniert:
https://www.loxforum.com/forum/projektforen/loxberry/plugins/74862-loxberry-sonos-plugin-verfügbar?p=167337#post167337

**Comment by christoph5180** [comment]
Das hatte ich zufällig grade ausprobiert. Wenn die Player manuell in die player.cfg eingetragen werden funktioniert es. Habe nur mal kurz tts und Jingle getestet.

Wie kommst du mit dem Scan Fix voran? Evtl. könnte ich dabei Unterstützung leisten.

**Comment by AngelNev** [comment]
Ich kann auch bestätigen, dass der Workaround funktioniert. Jedenfalls sehe ich nun die Geräte. Da es bei mir aber um eine Erstinstallation handelt, kann ich keine Funktionsabstriche oder -verbesserungen gegenüber vorher verlauten lassen. Für andere die das Plug-in das erste Mal installieren und die Version 9.1 haben: Die Geräte können manuell eingefügt werden, wie im Forum-Link von Liver64 beschrieben.

Das player.cfg befindet sich übringes auf dem Loxberry hier: /opt/loxberry/config/plugins/sonos4lox/player.cfg

Format im File:
```
[SONOSZONEN]
Black[]=192.168.22.236,RINCON_949F3E8438A201400,PLAY:1,50,30,100
Lounge II[]=192.168.22.230,RINCON_949F3E7439AA01400,PLAY:1,50,30,100
```

Ja, das Unterstützungsangebot mache ich auch. Bin aber kein Entwickler... Doku oder so ginge auch...

**Comment by Liver64** [comment]
please install Pre-release v3.4.7 and test
