### ISSUE TITLE
test von befehlen schlägt fehl

### ISSUE THREAD

**Issue by TheSpirit** [Liver64/LoxBerry-Sonos#2]
nach testen von 
`http://192.168.178.65/plugins/sonos4lox/index.php?zone=K&#220CHE&action=sendmessage&text=hallo.%20dies%20ist%20ein%20test&volume=20`
bekomme ich als rückmeldung

```
Warning: syntax error, unexpected '=' in /opt/loxberry/config/plugins/sonos4lox//player.cfg on line 6 in /opt/loxberry/webfrontend/html/plugins/sonos4lox/sonos2.php on line 51

Warning: Invalid argument supplied for foreach() in /opt/loxberry/webfrontend/html/plugins/sonos4lox/sonos2.php on line 54

Notice: Undefined variable: sonosnet in /opt/loxberry/webfrontend/html/plugins/sonos4lox/sonos2.php on line 57



Warning:  Invalid argument supplied for foreach() in /opt/loxberry/webfrontend/html/plugins/sonos4lox/sonos2.php on line 123



Notice:  Undefined variable: handle in /opt/loxberry/webfrontend/html/plugins/sonos4lox/sonos2.php on line 135



Warning:  fclose() expects parameter 1 to be resource, null given in /opt/loxberry/webfrontend/html/plugins/sonos4lox/sonos2.php on line 135




Notice:  Undefined variable: sonoszone in /opt/loxberry/webfrontend/html/plugins/sonos4lox/sonos2.php on line 229



Warning:  fsockopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /opt/loxberry/webfrontend/html/plugins/sonos4lox/system/PHPSonos.php on line 2633



Warning:  fsockopen(): unable to connect to :1400 (php_network_getaddresses: getaddrinfo failed: Name or service not known) in /opt/loxberry/webfrontend/html/plugins/sonos4lox/system/PHPSonos.php on line 2633



Fatal error:  Uncaught exception 'Exception' with message 'Error opening socket: php_network_getaddresses: getaddrinfo failed: Name or service not known (0)' in /opt/loxberry/webfrontend/html/plugins/sonos4lox/system/PHPSonos.php:2635
Stack trace:
#0 /opt/loxberry/webfrontend/html/plugins/sonos4lox/system/PHPSonos.php(1449): PHPSonos->sendPacket('POST /MediaRend...')
#1 /opt/loxberry/webfrontend/html/plugins/sonos4lox/sonos2.php(230): PHPSonos->GetVolume()
#2 /opt/loxberry/webfrontend/html/plugins/sonos4lox/index.php(7): require_once('/opt/loxberry/w...')
#3 {main}
  thrown in /opt/loxberry/webfrontend/html/plugins/sonos4lox/system/PHPSonos.php on line 2635

```

**Comment by Liver64** [comment]
Ohne gescannte und gespeicherte Zonen geht nichts! Außerdem ist die komplette Syntax immer in Kleinschreibung.
